# Generated by Django 6.0.3 on 2026-03-29 20:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keel_periods', '0001_initial'),
        ('keel_reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft — awaiting submissions'), ('complete', 'Complete — all approved'), ('signing', 'Signing — in Manifest'), ('signed', 'Signed — approved'), ('published', 'Published — distributed')], default='draft', max_length=20)),
                ('aggregated_data', models.JSONField(blank=True, default=dict)),
                ('variance_vs_prior', models.JSONField(blank=True, default=dict)),
                ('variance_vs_budget', models.JSONField(blank=True, default=dict)),
                ('compliance_summary', models.JSONField(blank=True, default=dict)),
                ('manifest_signing_id', models.UUIDField(blank=True, null=True)),
                ('executive_summary', models.TextField(blank=True)),
                ('pdf_export', models.FileField(blank=True, upload_to='close_packages/%Y/%m/')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('fiscal_period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purser_close_package', to='keel_periods.fiscalperiod')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fiscal_period__start_date'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('program_type', models.CharField(choices=[('grant', 'Grant'), ('loan', 'Loan'), ('tax_credit', 'Tax Credit'), ('bond', 'Bond Financing'), ('federal_passthrough', 'Federal Pass-Through'), ('other', 'Other')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('pulls_from_harbor', models.BooleanField(default=False)),
                ('harbor_api_endpoint', models.URLField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('report_schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purser_programs', to='keel_reporting.reportschema')),
                ('reviewers', models.ManyToManyField(blank=True, related_name='purser_program_reviews', to=settings.AUTH_USER_MODEL)),
                ('submitters', models.ManyToManyField(blank=True, related_name='purser_program_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('revision_requested', 'Revision Requested'), ('approved', 'Approved'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('harbor_pull', 'Auto-Pull from Harbor'), ('csv_import', 'CSV Import')], default='manual', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('fiscal_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purser_submissions', to='keel_periods.fiscalperiod')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='purser.program')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purser_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purser_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fiscal_period__start_date', 'program__name'],
                'unique_together': {('program', 'fiscal_period')},
            },
        ),
        migrations.CreateModel(
            name='SubmissionAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='submissions/attachments/%Y/%m/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='purser.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetBaseline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annual_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monthly_spread', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purser_budgets', to='keel_periods.fiscalyear')),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purser_budgets', to='keel_reporting.reportlineitem')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='purser.program')),
            ],
            options={
                'unique_together': {('program', 'fiscal_year', 'line_item')},
            },
        ),
        migrations.CreateModel(
            name='SubmissionLineValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('text_value', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purser_values', to='keel_reporting.reportlineitem')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_values', to='purser.submission')),
            ],
            options={
                'unique_together': {('submission', 'line_item')},
            },
        ),
    ]
