# Generated by Django 6.0.3 on 2026-04-19 17:18

import keel.security.scanning
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purser', '0002_submissionstatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closepackage',
            name='pdf_export',
            field=models.FileField(blank=True, upload_to='close_packages/%Y/%m/', validators=[keel.security.scanning.FileSecurityValidator()]),
        ),
        migrations.AlterField(
            model_name='submissionattachment',
            name='file',
            field=models.FileField(upload_to='submissions/attachments/%Y/%m/', validators=[keel.security.scanning.FileSecurityValidator()]),
        ),
    ]
