# Generated by Django 6.0.3 on 2026-04-23 23:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purser', '0003_alter_closepackage_pdf_export_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosePackageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('external', 'External (applicant-visible)'), ('internal', 'Internal (staff-only)')], default='internal', max_length=10)),
                ('source', models.CharField(choices=[('upload', 'Manually uploaded'), ('manifest_signed', 'Signed document returned from Manifest'), ('system', 'System-generated')], default='upload', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('manifest_packet_uuid', models.CharField(blank=True, max_length=64)),
                ('close_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='purser.closepackage')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Close Package Attachment',
                'verbose_name_plural': 'Close Package Attachments',
                'ordering': ['-uploaded_at'],
                'abstract': False,
            },
        ),
    ]
